

# basic options
title: COMMUNICATION
author: GitHub User
email: your-email@domain.com
description:
twitter_username: jekyllrb
github_username:  guptaarjunkumar

# Build settings
markdown: kramdown
theme:  jekyll-theme-tactile
